services:
  jtl-connector-distributor-nginx:
    networks:
      - default
      - shared-net
    image: nginx:latest
    container_name: jtl-connector-distributor-nginx
    ports:
      - "8282:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - jtl-connector-distributor-php

  jtl-connector-distributor-php:
    networks:
      - default
      - shared-net
    build:
      context: ./.docker/php
    container_name: jtl-connector-distributor-php
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"
    depends_on:
      - jtl-connector-distributor-db

  jtl-connector-distributor-db:
    image: mysql:8.0
    container_name: jtl-connector-distributor-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ROOT
      MYSQL_DATABASE: jtl-connector
      MYSQL_USER: jtl-connector
      MYSQL_PASSWORD: jtl-connector
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  db_data:

networks:
  shared-net:
    external: true
